language: node_js
node_js:
  - "0.12"
sudo: false

before_install:
    - export SAUCE_USERNAME=rev087
    - export SAUCE_ACCESS_KEY=8247a039-7c68-484e-ae27-a8f2ef94c47f

addons:
  sauce_connect: true
